### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by calebheinzman** [Deep-Stonks-Group/PythonDataProcessing#4]
`Traceback (most recent call last):
  File "/Users/calebheinzman/Documents/Workspace/PyCharm Projects/Stocks/Forecast-Team-1/simple_lstm/torchLSTM.py", line 194, in <module>
    predictor.train_ticker('GOOGL')
  File "/Users/calebheinzman/Documents/Workspace/PyCharm Projects/Stocks/Forecast-Team-1/simple_lstm/torchLSTM.py", line 131, in train_ticker
    stock_dataframe = retrieve_stock_data(ticker, self.input_dims, self.label_dims)
  File "/Users/calebheinzman/Documents/Workspace/PyCharm Projects/Stocks/Forecast-Team-1/simple_lstm/torchLSTM.py", line 53, in retrieve_stock_data
    data_source = DR.get_stock_data(ticker,interval='1d',period='2y')
  File "/Users/calebheinzman/.conda/envs/pythonProject/lib/python3.8/site-packages/PythonDataProcessing/DataRetrieval.py", line 76, in get_stock_data
    return stock.history(period=period, interval=interval)
  File "/Users/calebheinzman/.conda/envs/pythonProject/lib/python3.8/site-packages/yfinance/base.py", line 157, in history
    data = data.json()
  File "/Users/calebheinzman/.conda/envs/pythonProject/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/calebheinzman/.conda/envs/pythonProject/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/calebheinzman/.conda/envs/pythonProject/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/calebheinzman/.conda/envs/pythonProject/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by calebheinzman** [comment]
To fix this use:

`pip uninstall yfinance`
`pip install yfinance --upgrade --no-cache-dir`

Source: https://stackoverflow.com/questions/68331065/json-decode-error-with-yfinance-jsondecodeerror-expecting-value-line-1-column
